# Generated by Django 3.0.8 on 2020-10-01 00:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryname', models.CharField(max_length=120)),
                ('department', models.CharField(blank=True, max_length=120, null=True)),
                ('campus', models.CharField(blank=True, max_length=120, null=True)),
                ('createtime', models.DateTimeField(blank=True, max_length=120, null=True)),
                ('createuser', models.CharField(blank=True, max_length=120, null=True)),
                ('lastupdatetime', models.CharField(blank=True, max_length=120, null=True)),
                ('lastupdateuser', models.DateTimeField(blank=True, max_length=120, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FileInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=120)),
                ('filesize', models.DecimalField(decimal_places=0, max_digits=10)),
                ('filepath', models.CharField(blank=True, max_length=120, null=True)),
                ('uploadtime', models.DateTimeField(blank=True, null=True)),
                ('uploaduser', models.CharField(blank=True, max_length=120, null=True)),
                ('department', models.CharField(blank=True, max_length=120, null=True)),
                ('campus', models.CharField(blank=True, max_length=120, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docmgt.Category')),
            ],
        ),
    ]
