# Generated by Django 3.0.8 on 2020-11-27 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docmgt', '0003_category_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='permissionname',
            field=models.CharField(blank=True, max_length=520, null=True),
        ),
    ]
