# Generated by Django 4.0.5 on 2024-07-17 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docmgt', '0004_category_permissionname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='fileinfo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
