# Generated by Django 3.0.8 on 2020-08-21 01:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ybielearning', '0002_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrolleduser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=120, null=True)),
                ('fullname', models.CharField(blank=True, max_length=120, null=True)),
                ('suspended', models.CharField(blank=True, max_length=120, null=True)),
                ('courseid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ybielearning.Course')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ybielearning.User')),
            ],
        ),
    ]
