# Generated by Django 3.0.8 on 2020-08-21 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ybielearning', '0003_enrolleduser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrolleduser',
            name='courseid',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='enrolleduser',
            name='userid',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
