# Generated by Django 3.0.8 on 2020-08-21 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ybielearning', '0004_auto_20200821_0141'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryid', models.CharField(max_length=120)),
                ('categoryname', models.CharField(max_length=120)),
            ],
        ),
    ]
