# Generated by Django 3.0.8 on 2020-08-24 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ybielearning', '0005_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrolleduser',
            name='roleid',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='enrolleduser',
            name='rolename',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
