# Generated by Django 3.0.8 on 2020-08-25 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ybielearning', '0006_auto_20200825_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='categoryname',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
