# Generated by Django 3.0.8 on 2020-09-07 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ybielearning', '0007_course_categoryname'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='priority',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
