# Generated by Django 3.0.8 on 2020-10-26 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ybielearning', '0009_bbbbn_logs_bbbrecordings_bbbrecordingsview'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBulk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=120, null=True)),
                ('firstname', models.CharField(blank=True, max_length=120, null=True)),
                ('lastname', models.CharField(blank=True, max_length=120, null=True)),
                ('password', models.CharField(blank=True, max_length=120, null=True)),
                ('email', models.CharField(blank=True, max_length=120, null=True)),
                ('createdtime', models.DateTimeField(blank=True, null=True)),
                ('createduser', models.CharField(blank=True, max_length=120, null=True)),
                ('synctime', models.DateTimeField(blank=True, null=True)),
                ('syncuser', models.CharField(blank=True, max_length=120, null=True)),
                ('randomkey', models.CharField(blank=True, max_length=120, null=True)),
            ],
        ),
    ]
