# Generated by Django 4.0.5 on 2024-07-20 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campus', models.CharField(max_length=120)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('path', models.CharField(max_length=120)),
                ('givenname', models.CharField(max_length=120)),
                ('surname', models.CharField(max_length=120)),
                ('samaccountname', models.CharField(max_length=120)),
                ('displayname', models.CharField(max_length=120)),
                ('password', models.CharField(max_length=120)),
            ],
        ),
    ]
