# Generated by Django 4.0.5 on 2024-08-16 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aduser', '0002_student_is_in_ad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='givenname',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='surname',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
