# Generated by Django 4.0.5 on 2024-08-16 22:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('aduser', '0003_alter_student_givenname_alter_student_surname'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='createdtime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
