# Generated by Django 4.0.5 on 2024-08-16 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aduser', '0004_student_createdtime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='createdtime',
            new_name='createdtime_utc',
        ),
    ]
