# Generated by Django 4.0.5 on 2024-08-17 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aduser', '0005_rename_createdtime_student_createdtime_utc'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
