# Generated by Django 4.0.5 on 2024-08-17 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aduser', '0006_student_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_in_Elearning',
            field=models.CharField(default='n', help_text='y means yes, n means no', max_length=1),
        ),
    ]
