# Generated by Django 3.0.8 on 2020-09-09 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbielearning', '0003_auto_20200909_0133'),
    ]

    operations = [
        migrations.AddField(
            model_name='bbbbn_logs',
            name='bigbluebuttonbnid',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='bbbbn_logs',
            name='meta',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
    ]
