# Generated by Django 3.0.8 on 2020-09-17 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbielearning', '0004_auto_20200909_0155'),
    ]

    operations = [
        migrations.CreateModel(
            name='BBBRecordingsView',
            fields=[
                ('id', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('recordid', models.CharField(blank=True, max_length=120, null=True)),
                ('meetingid', models.CharField(blank=True, max_length=120, null=True)),
                ('name', models.CharField(blank=True, max_length=120, null=True)),
                ('published', models.CharField(blank=True, max_length=120, null=True)),
                ('state', models.CharField(blank=True, max_length=120, null=True)),
                ('starttime', models.CharField(blank=True, max_length=120, null=True)),
                ('endtime', models.CharField(blank=True, max_length=120, null=True)),
                ('courseid', models.CharField(blank=True, max_length=120, null=True)),
                ('coursename', models.CharField(blank=True, max_length=120, null=True)),
                ('categoryid', models.CharField(blank=True, max_length=120, null=True)),
                ('categoryname', models.CharField(blank=True, max_length=120, null=True)),
            ],
            options={
                'db_table': 'bbielearning_bbbrecordings_view',
            },
        ),
    ]
