# Generated by Django 3.0.8 on 2020-09-29 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbielearning', '0006_userbulk'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbulk',
            name='createdtime',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='userbulk',
            name='createduser',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='userbulk',
            name='randomkey',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='userbulk',
            name='synctime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userbulk',
            name='syncuser',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
