# Generated by Django 3.0.8 on 2020-09-29 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbielearning', '0007_auto_20200929_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbulk',
            name='createdtime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='userbulk',
            name='synctime',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
