# Generated by Django 3.0.8 on 2020-09-30 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbielearning', '0008_auto_20200929_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbulk',
            name='createdtime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userbulk',
            name='synctime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
