# Generated by Django 3.0.8 on 2020-11-09 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbielearning', '0009_auto_20200930_1216'),
    ]

    operations = [
        migrations.CreateModel(
            name='BBBRecordings_Old',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recordid', models.CharField(blank=True, max_length=120, null=True)),
                ('meetingid', models.CharField(blank=True, max_length=120, null=True)),
                ('name', models.CharField(blank=True, max_length=120, null=True)),
                ('published', models.CharField(blank=True, max_length=120, null=True)),
                ('state', models.CharField(blank=True, max_length=120, null=True)),
                ('starttime', models.CharField(blank=True, max_length=120, null=True)),
                ('endtime', models.CharField(blank=True, max_length=120, null=True)),
            ],
        ),
    ]
