# Generated by Django 3.0.8 on 2021-01-12 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbielearning', '0010_bbbrecordings_old'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAssignTrainer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseid', models.CharField(blank=True, max_length=120, null=True)),
                ('userid', models.CharField(blank=True, max_length=120, null=True)),
                ('username', models.CharField(blank=True, max_length=120, null=True)),
                ('fullname', models.CharField(blank=True, max_length=120, null=True)),
                ('trainername', models.CharField(blank=True, max_length=120, null=True)),
                ('roleid', models.CharField(blank=True, max_length=120, null=True)),
                ('rolename', models.CharField(blank=True, max_length=120, null=True)),
                ('suspended', models.CharField(blank=True, max_length=120, null=True)),
            ],
        ),
    ]
