# Generated by Django 3.0.8 on 2020-10-13 19:08

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('department', models.CharField(max_length=120)),
                ('campus', models.CharField(blank=True, max_length=120, null=True)),
                ('top', models.CharField(blank=True, max_length=120, null=True)),
                ('email', models.BooleanField(default=True)),
                ('postdate', models.DateTimeField(blank=True, null=True)),
                ('postuser', models.CharField(blank=True, max_length=120, null=True)),
                ('updatedate', models.DateTimeField(blank=True, null=True)),
                ('updateuser', models.CharField(blank=True, max_length=120, null=True)),
            ],
        ),
    ]
