# Generated by Django 3.0.8 on 2020-10-20 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academiccalendar',
            name='finishdate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='academiccalendar',
            name='intakedate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='academiccalendar',
            name='startdate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
