# Generated by Django 3.0.8 on 2020-10-20 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_auto_20201021_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academiccalendar',
            name='campus',
            field=models.CharField(blank=True, choices=[('ybi', 'ybi'), ('bbi', 'bbi')], max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='academiccalendar',
            name='term',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='academiccalendar',
            name='year',
            field=models.CharField(choices=[('2020', '2020'), ('2021', '2021'), ('2022', '2022'), ('2023', '2023')], max_length=120),
        ),
    ]
