# Generated by Django 4.0.5 on 2024-07-17 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0003_auto_20201021_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academiccalendar',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
