# Generated by Django 3.0.8 on 2020-10-03 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20201001_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='C:\\project\\wellington\\media\\profilepics'),
        ),
    ]
