# Generated by Django 3.0.8 on 2020-09-17 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('it', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staffbirthday',
            old_name='data',
            new_name='datetime',
        ),
    ]
