# Generated by Django 3.0.8 on 2020-09-17 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('it', '0002_auto_20200917_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffbirthday',
            name='datetime',
            field=models.DateField(),
        ),
    ]
