# Generated by Django 3.0.8 on 2020-09-17 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('it', '0003_auto_20200917_1702'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staffbirthday',
            old_name='datetime',
            new_name='birthdaydate',
        ),
    ]
