# Generated by Django 3.0.8 on 2020-09-18 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('it', '0005_auto_20200918_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffbirthday',
            name='adddate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staffbirthday',
            name='birthdaydate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
