# Generated by Django 3.0.8 on 2020-09-18 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('it', '0006_auto_20200918_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffbirthday',
            name='adddate',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
