# Generated by Django 4.0.5 on 2024-07-17 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('it', '0007_auto_20200918_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffbirthday',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
