name: Deploy Intranet to 10.5.0.10

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 检出代码
      - name: Checkout Code
        uses: actions/checkout@v2

      # 登录到 Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 构建并推送 Docker 镜像
      - name: Build and Push Docker Image
        run: |
          docker build -t your-dockerhub-username/intranet:latest .
          docker push your-dockerhub-username/intranet:latest

      # 部署到服务器
      - name: Deploy to Server
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          script: |
            docker pull your-dockerhub-username/intranet:latest
            docker stop intranet-container || true
            docker rm intranet-container || true
            docker run -d --name intranet-container -p 5002:8000 your-dockerhub-username/intranet:latest 