name: Deploy to Server

on:
  push:
    branches:
      - main  # 当推送到 main 分支时触发

jobs:
  deploy:
    runs-on: self-hosted  # 使用自托管运行器
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      # 示例部署步骤
      - name: Deploy to Server
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          script: |
            docker pull selwyn11/myapp:latest
            docker stop myapp-container || true
            docker rm myapp-container || true
            docker run -d --name myapp-container -p 5002:5002 selwyn11/myapp:latest
          debug: true
