name: Deploy to Server with SSH

on:
  push:
    branches:
      - main  # 在推送到 main 分支时触发部署

jobs:
  deploy:
    runs-on: self-hosted  # 使用你的自托管运行器

    steps:
      # 检出代码
      - name: Checkout code
        uses: actions/checkout@v2

      # 设置 SSH Key 文件
      - name: Set up SSH key
        env:
          SSH_KEY: ${{ secrets.SERVER_SSH_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_KEY" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key

      # 执行部署
      - name: Deploy to Server
        env:
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/deploy_key -p 22 $SERVER_USER@$SERVER_HOST << 'EOF'
            docker pull selwyn11/myapp:latest
            docker stop myapp-container || true
            docker rm myapp-container || true
            docker run -d --name myapp-container -p 5002:5002 selwyn11/myapp:latest
          EOF
